config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :surveys, only: [:index, :show]

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :surveys, only: [:index, :show, :create, :update, :destroy]
      resources :votes, only: [:create]
    end
  end
end

app/models/identity.rb
class Identity < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_creaty_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :survey
  has_many :votes, dependent: :destroy
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :user
  has_many :options, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :surveys, dependent: :destroy
  validates :email, presence: true, uniqueness: true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :option
end

app/controllers/api/v1/surveys_controller.rb
class Api::V1::SurveysController < ApplicationController
  respond_to :json
  before_action :set_survey, only: [:show, :update, :destroy]

  def index
    respond_with current_user.surveys.order(active: :desc)
  end

  def show
    options = @survey.options
    votes = count_votes(options)
    data = {survey: @survey, options: options, votes: votes}
    respond_with data
  end

  def create
    create_survey_with_options(params)
    render json: "success"
  end

  def update
    @survey.update_attributes(active: false);
    render json: "success"
  end

  def destroy
    @survey.destroy
    render json: "success"
  end

  private

  def count_votes(options)
    options.map do |option|
      option.votes.count
    end
  end

  def set_survey
    @survey = Survey.find(params[:id])
  end

end

app/controllers/api/v1/votes_controller.rb
class Api::V1::VotesController < ApplicationController
  respond_to :json

  def create
    Vote.create(option_id: params[:optionId])
    render json: "success"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user,
                :authorize,
                :create_survey_with_options

  def current_user
    @user = User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    unless current_user
      redirect_to root_path
      flash[:error] = "Please login first"
    end
  end

  def create_survey_with_options(params)
    survey_params = params["survey"]
    @survey = Survey.create(user_id: current_user.id,
                            name: survey_params["surveyName"],
                            question: survey_params["surveyQuestion"],
                            expiration: survey_params["surveyExpiration"])
    survey_params["surveyOptions"].each do |option|
      @option = Option.create(survey_id: @survey.id,
                              title: option)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to surveys_path
    end
  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to surveys_path
    else
      flash.now[:error] = "Invalid Credentials"
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Succesfully logged out!"
    redirect_to login_path
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
    before_action :authorize, only: [:index]

  def index
    @surveys = current_user.surveys
  end

  def show
    @params = params
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Logged in as #{@user.email}"
      redirect_to surveys_path
    else
      flash.now[:error] = "Invalid Credentials"
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flashes/_flashes.html.erb
<div class="container">
  <% flash.each do |type, msg| %>
    <div class="card">
      <p><center><%= content_tag :div, msg.html_safe %></center></p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poll Machine</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= favicon_link_tag 'poll.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "flashes/flashes" %>
  <%= render partial: "navbar/navbar" %>
  <%= yield %>
</body>
</html>

app/views/navbar/_navbar.html.erb
<nav class="captain-background">
    <a class="brand-logo" style="padding-left:3%" href="/">Poll Machine</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <% unless current_user %>
        <li><%= link_to "Login", login_path %></li>
        <li><%= link_to "Sign Up", new_user_path %></li>
      <% end %>
        <li><%= link_to "Logout", logout_path, method: :delete %></li>
    </ul>
</nav>

app/views/scripts/_chart.html.erb
<script src="Chart.js"></script>
<script>
    var myChart = new Chart({...})
</script>

app/views/scripts/_facebook_button.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/scripts/_twitter_button.html.erb
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/surveys/index.html.erb
<%= react_component 'Main' %>

app/views/surveys/show.html.erb
<%= react_component('App', {params: params }) %>

<%= render partial: "scripts/facebook_button" %>
<%= render partial: "scripts/twitter_button" %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.6/Chart.js"></script>

app/views/users/new.html.erb
<div class="container">
  <h1>Sign Up</h1>

  <%= form_for(@user) do |f| %>
    <%= f.label :email_address %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Create Account" %>
  <% end %>
</div>